import { Pool } from "pg";

const pool = new Pool({
    user: "postgres",
    password: "postgres",
    database: "book_api",
    port: 5432
});

const authors = [
    {
        name: "Robert C. Martin",
        email: "robert.martin@example.com"
    },
    {
        name: "Martin Fowler",
        email: "martin.fowler@example.com"
    },
    {
        name: "Andrew Hunt",
        email: "andrew.hunt@example.com"
    },
    {
        name: "David Thomas",
        email: "david.thomas@example.com"
    },
    {
        name: "James Clear",
        email: "james.clear@example.com"
    }
];

const books: [email: string, title: string][] = [
    ["robert.martin@example.com", "Clean Code"],
    ["robert.martin@example.com", "The Clean Coder"],
    ["robert.martin@example.com", "Clean Architecture"],
    ["robert.martin@example.com", "Agile Software Development"],
    ["robert.martin@example.com", "Working Effectively with Legacy Code"],
    ["robert.martin@example.com", "Designing Object-Oriented C++ Applications"],
    ["robert.martin@example.com", "Principles, Patterns, and Practices of Agile Software Development"],
    ["robert.martin@example.com", "The Principles of Object-Oriented Design"],

    ["martin.fowler@example.com", "Refactoring"],
    ["martin.fowler@example.com", "Patterns of Enterprise Application Architecture"],
    ["martin.fowler@example.com", "Domain-Specific Languages"],
    ["martin.fowler@example.com", "NoSQL Distilled"],
    ["martin.fowler@example.com", "Analysis Patterns"],
    ["martin.fowler@example.com", "UML Distilled"],
    ["martin.fowler@example.com", "Implementing Domain-Specific Languages"],
    ["martin.fowler@example.com", "Evolutionary Architecture"],

    ["andrew.hunt@example.com", "The Pragmatic Programmer"],
    ["andrew.hunt@example.com", "Pragmatic Thinking and Learning"],
    ["andrew.hunt@example.com", "The Pragmatic Programmer: 20th Anniversary Edition"],
    ["andrew.hunt@example.com", "Debugging: The 9 Indispensable Rules"],
    ["andrew.hunt@example.com", "Programming Pearls"],
    ["andrew.hunt@example.com", "Pragmatic Unit Testing"],
    ["andrew.hunt@example.com", "Pragmatic Version Control"],
    ["andrew.hunt@example.com", "The Pragmatic Bookshelf"],

    ["david.thomas@example.com", "Programming Ruby"],
    ["david.thomas@example.com", "Programming Elixir"],
    ["david.thomas@example.com", "Agile Web Development with Rails"],
    ["david.thomas@example.com", "Programming Erlang"],
    ["david.thomas@example.com", "Metaprogramming Ruby"],
    ["david.thomas@example.com", "Programming Phoenix"],
    ["david.thomas@example.com", "The Ruby Programming Language"],
    ["david.thomas@example.com", "Programming Ruby 3.3"],

    ["james.clear@example.com", "Atomic Habits"],
    ["james.clear@example.com", "Habits and Goals"],
    ["james.clear@example.com", "The Habit Journal"],
    ["james.clear@example.com", "Small Changes, Big Results"],
    ["james.clear@example.com", "Building Better Systems"],
    ["james.clear@example.com", "Daily Habits"],
    ["james.clear@example.com", "The Power of Consistency"],
    ["james.clear@example.com", "Mastering Your Habits"]
];

async function seed() {
    try {
        await pool.query("BEGIN");

        // Insert authors
        for (const author of authors) {
            await pool.query(
                `
                INSERT INTO author (name, email)
                VALUES ($1, $2)
                ON CONFLICT (email) DO NOTHING
                `,
                [author.name, author.email]
            );
        }

        // Get the actual IDs generated by PostgreSQL
        const authorResult = await pool.query<{
            id: number;
            email: string;
        }>(
            "SELECT id, email FROM author"
        );

        const authorIds = new Map<string, number>();

        for (const author of authorResult.rows) {
            authorIds.set(author.email, author.id);
        }

        // Insert books
        for (const [email, title] of books) {
            const authorId = authorIds.get(email);

            if (authorId === undefined) {
                throw new Error(
                    `Author not found for email: ${email}`
                );
            }

            await pool.query(
                `
                INSERT INTO book (author_id, title)
                VALUES ($1, $2)
                `,
                [authorId, title]
            );
        }

        await pool.query("COMMIT");

        console.log("Seed completed successfully");
        console.log(`Authors processed: ${authors.length}`);
        console.log(`Books inserted: ${books.length}`);
    } catch (error) {
        await pool.query("ROLLBACK");

        console.error("Seed failed:");
        console.error(error);
    } finally {
        await pool.end();
    }
}

seed();